const express = require("express")
const auth = require("../middleware/auth")
const formController = require("../controller/form")
const validation = require("../middleware/validation")

module.exports = express
  .Router()
  .post("/forms", auth, validation("formCreate", "body"), formController.formCreate)
  .get("/forms", auth, formController.getAllForms)
  .get("/forms/:uuid", auth, validation("uuid", "params"), formController.getOneForm)
  .put("/forms/:uuid", auth, validation("uuid", "params"), validation("formUpdate", "body"), formController.formUpdate)
  .post("/forms/:uuid/submit", auth, validation("uuid", "params"), validation("submitForm", "body"), formController.submitForm)
  .delete("/forms/:uuid", auth, validation("uuid", "params"), formController.deleteForm)
  .get("/forms/:uuid/response", auth, validation("uuid", "params"), formController.getFormResponse)
  .post("/forms/:uuid/copy", auth, validation("uuid", "params"), formController.copyForm)
